---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: elasticsearch-self-signed
  namespace: elasticsearch
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elasticsearch-ca
  namespace: elasticsearch
spec:
  commonName: internode
  isCA: true
  issuerRef:
    kind: Issuer
    name: elasticsearch-self-signed
  secretName: elasticsearch-ca