---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.7.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true 
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kibana-certificate
  namespace: elastic-system
spec:
  secretName: kibana-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - kibana.phuongn.dev
    - '*.kibana.phuongn.dev'
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elastic-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - kibana.phuongn.dev
        - '*.kibana.phuongn.dev'
      secretName: kibana-secret
  rules:
    - host: kibana.phuongn.dev
      http:
        paths:
          - backend:
              serviceName: kibana-kb-http
              servicePort: 5601
---