apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: logs
spec:
  secretName: logs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - logs.phuongn.dev
    - www.logs.phuongn.dev