apiVersion: v1
kind: Namespace
metadata:
  name: portfolio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: portfolio-system
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: phuongnse/portfolio:12
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio-system
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: portfolio
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: portfolio-certificate
  namespace: portfolio-system
spec:
  secretName: portfolio-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - phuongn.dev
    - www.phuongn.dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - phuongn.dev
        - www.phuongn.dev
      secretName: portfolio-secret
  rules:
    - host: phuongn.dev
      http:
        paths:
          - backend:
              serviceName: portfolio-service
              servicePort: 3000