# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=&oem=esse&user=11cb8cd8-93f8-11ea-97e6-f6e09c7a4e5e&b=true&c=px-cluster-3a38158c-b025-4dc6-90a8-dbf67fa7f76c&stork=true&lh=true&st=k8s
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-3a38158c-b025-4dc6-90a8-dbf67fa7f76c
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=&oem=esse&user=11cb8cd8-93f8-11ea-97e6-f6e09c7a4e5e&b=true&c=px-cluster-3a38158c-b025-4dc6-90a8-dbf67fa7f76c&stork=true&lh=true&st=k8s"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:2.6.3
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  userInterface:
    enabled: true
  autopilot:
    enabled: true
    providers:
    - name: default
      type: prometheus
      params:
        url: http://prometheus:9090
---
apiVersion: v1
kind: Secret
metadata:
  name: px-essential
  namespace: kube-system
data:
  px-essen-user-id: MTFjYjhjZDgtOTNmOC0xMWVhLTk3ZTYtZjZlMDljN2E0ZTVl
  px-osb-endpoint: aHR0cHM6Ly9weGVzc2VudGlhbHMucG9ydHdvcnguY29tL29zYi9iaWxsaW5nL3YxL3JlZ2lzdGVy
